### ISSUE TITLE
I/O timeouts when replaying traffic at ~550 rps

### ISSUE THREAD

**Issue by raags** [buger/goreplay#361] opened 2016-08-26 06:19 UTC
I'm running a benchmark that captures and sends non keep-alive http requests using gor. It mostly works, but sometimes I see the following in the logs :

```
2016/08/26 06:05:20 [HTTPClient] Connection error: dial tcp 10.226.137.165:9003: i/o timeout
2016/08/26 06:05:20 [HTTPClient] Connection error: dial tcp 10.226.137.165:9003: i/o timeout
2016/08/26 06:05:20 [HTTPClient] Connection error: dial tcp 10.226.137.165:9003: i/o timeout
2016/08/26 06:05:20 [HTTPClient] Connection error: dial tcp 10.226.137.165:9003: i/o timeout
2016/08/26 06:05:20 [HTTPClient] Connection error: dial tcp 10.226.137.165:9003: i/o timeout
2016/08/26 06:05:20 [HTTPClient] Connection error: dial tcp 10.226.137.165:9003: i/o timeout
```

Does this indicate a problem with my target server? How do I enable http keep alive from gor?

**Comment by buger** [comment] 2016-08-31 13:42
Hello! It looks like problems with your server, since error happens while trying to open new connection. By default, timeout is 5 seconds (both connection and read/write), and you can change it using `--output-http-timeout` option.

Regarding keep-alive, by default Gor keeps a pool of connections and auto-scale it, you can try to disable auto-scaling and turn on fixed number of connections to your server using `--output-http-workers` option.

GoReplay PRO https://goreplay.org/pro.html also offers recording and replaying keep-alive sessions as-is, which brings it even closer to the production like environment https://github.com/buger/gor/wiki/%5BPRO%5D-Recording-and-replaying-keep-alive-TCP-sessions

**Comment by buger** [comment] 2016-12-27 17:28
Will close it for now

**Closed by buger** 2016-12-27 17:28 UTC

**Comment by MatteoOreficeIT** [comment] 2019-06-13 14:08
Hi

I have the same problem inside docker, the strange thing is the telnet binary can regularly connect to HOST:PORT supplied to gor, and without any timeout !!!

I have a custom gor image based on https://hub.docker.com/r/buger/goreplay/

```Dockerfile
FROM alpine:latest as builder
RUN apk add --no-cache ca-certificates openssl
RUN apk add busybox-extras
RUN wget https://github.com/buger/goreplay/releases/download/v0.16.1/gor_0.16.1_x64.tar.gz -O gor.tar.gz
RUN tar xzf gor.tar.gz
CMD ["./goreplay"]
```

I have added telnet binary with `RUN apk add busybox-extras` and removed ENTRYPOINT so I can run sh

After I executed 

```bash
goreplay -verbose -input-file '/usr/local/src/gor-data/*' \
                -output-http-header 'Host: 172.29.1.75:8166' \
                -output-http http://172.29.1.75:8166/ping -output-http-timeout 60s
```

## OUTPUT

```txt
Version: 0.16.1
[DEBUG][PID 286][1560434560190887200][1560434560190.887207ms] [HTTPClient] Connecting: http://172.29.1.75:8166/ping
[DEBUG][PID 286][1560434561643545900][1452.658700ms] [HTTPClient] Connecting: http://172.29.1.75:8166/ping
[DEBUG][PID 286][1560434561644313900][0.768000ms] [HTTPClient] Connecting: http://172.29.1.75:8166/ping
[DEBUG][PID 286][1560434565195235300][3550.921400ms] [HTTPClient] Response read timeout error read tcp 172.17.0.3:50376->172.29.1.75:8166: i/o timeout &{{0xc8200460e0}} 0
[DEBUG][PID 286][1560434565195969000][0.733700ms] [HTTP] Disconnected:  http://172.29.1.75:8166/ping
[DEBUG][PID 286][1560434565196505000][0.536000ms] Request error: read tcp 172.17.0.3:50376->172.29.1.75:8166: i/o timeout
[DEBUG][PID 286][1560434565197990300][1.485300ms] [HTTPClient] Connecting: http://172.29.1.75:8166/ping
```

## TELNET

```bash
telnet 172.29.1.75 8166
```

input from terminal

```txt
POST /ping
Host: 172.29.1.75:8166
```

## OUTPUT

```txt
HTTP/1.0 200 OK
Cache-Control: no-cache, private
Date:          Thu, 13 Jun 2019 14:03:45 GMT

pong

Connection closed by foreign host
```

## recorder data sample

```txt
POST /ping HTTP/1.1
Host: 172.201.34.188
Connection: close
Content-Length: 581
User-Agent: Mozilla/5.0 (compatible; pycurl)
Accept: */*
Accept-Encoding: gzip,deflate
Content-Type: application/x-www-form-urlencoded

{"msg": {"to": "5ae04aa00d7ba70006616dd1", "from": "3231893e-9971-4dc2-a462-6210da61825d", "devicetimestamp": "2019-04-02T10:10:27+00:00", "sdkclient": {"name": "CapsulatriceIottlyApp"}, "timestamp": "2019-04-02T10:10:27.755718+00:00", "type": "userdefined", "payload": {"data": {"rv": 0.8827842408837611, "rq": 0.9925249169435211, "rejectedUnits": 144, "availableTime": "1:42:56", "unitsPerHour": 0, "rf": 0.277854935034953, "downTime": "4:27:31", "oee": 0.24345242499274203, "totalUnits": 19264}, "tag": "CAPS", "type": "tel", "prodLine": "ABA1", "name": "TECMES"}}}

```

**Comment by MatteoOreficeIT** [comment] 2019-06-14 09:14
Hi have an update, we checked out initially the  0.16.1 version which gave us a connection error, but with the v1.0.0 the error is different, the connection is closed for each request without error, so I tried to analyze the incoming request on our server

We discovered the problem was an incorrect EOL in the recorded data that was under VCS, on git checkout a wrong autocrlf/.gitattributes remove CR from recorded data and the server cannot understand well the goreplay request stream

**So this is not a bug**, I suggest to use **-output-http-track-response** but in the 0.16.1 it did work
