### ISSUE TITLE
Paniced when replay from file.

### ISSUE THREAD

**Issue by hardvintage** [buger/goreplay#537] opened 2017-12-12 09:51 UTC
version:0.16.1

2017/12/12 09:19:50 [HTTPClient] Response:
2017/12/12 09:19:50 PANIC: pkg: runtime error: invalid memory address or nil pointer dereference goroutine 645315 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc826263c58, 0xc826263c70)
	/go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc8200140e0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
crypto/tls.(*Conn).writeRecord(0xc83a1cc600, 0xc828aa1e16, 0xc828aa1ec0, 0xb2, 0xb2, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:769 +0x542
crypto/tls.(*Conn).clientHandshake(0xc83a1cc600, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:147 +0xfba
crypto/tls.(*Conn).Handshake(0xc83a1cc600, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1033 +0xec
main.(*HTTPClient).Connect(0xc830c52500, 0x7f5b00225f20, 0xc83a1c7ea0)
	/go/src/github.com/buger/goreplay/http_client.go:98 +0x38a
main.(*HTTPClient).Send(0xc830c52500, 0xc83a1d46ff, 0x1e8, 0x1e8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/http_client.go:154 +0x32b5
main.(*HTTPOutput).sendRequest(0xc820012550, 0xc830c52500, 0xc83a1d46c0, 0x227, 0x227)
	/go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).startWorker(0xc820012550)
	/go/src/github.com/buger/goreplay/output_http.go:125 +0x1c7
created by main.(*HTTPOutput).workerMaster
	/go/src/github.com/buger/goreplay/output_http.go:99 +0x85

**Comment by slimus** [comment] 2020-06-03 10:23
Hi @hardvintage ! Duplicate of #545 . Please try version v1.0.0 or master branch

**Closed by slimus** 2020-06-03 10:24 UTC
