### ISSUE TITLE
Gor silently disconnect

### ISSUE THREAD

**Issue by exklamationmark** [buger/goreplay#368] opened 2016-09-22 03:56 UTC
Hi,

When I run `gor`, sometimes it will silently stop while forwarding HTTP requests.
My setup:

```
# this is running in a first host (a docker)
gor --input-raw :80 <a bunch of HTTP allow/disallow>  --output-http 'http://target.host:25880' --debug --verbose > /tmp/gor.debug 2>&1
```

When it stop, I see this at the end of the debug log

```
...


[DEBUG][PID 18337][1474510621022063052][0.048983ms] [HTTPClient] Connecting: http://target.host:25880
[DEBUG][PID 18337][1474510621022122478][0.059426ms] [HTTP] Disconnected:  http://target.host:25880
```

This seems that gor teminated at some point after this line:
https://github.com/buger/gor/blob/master/http_client.go#L158
and before this line:
https://github.com/buger/gor/blob/master/http_client.go#L178
but no error was recorded.

It seems `SetWriteDeadline` is a candidate, but i am using the default config, so `timeout` should be 0 and thus there's no deadline.

I would appreciate any pointers to understand why this happen.

This can be reproduced this quite reliably, so I can put more debug log/strace as needed

**Comment by buger** [comment] 2016-09-22 10:15
Hello! The default timeout is [5 seconds](https://github.com/buger/gor/blob/master/http_client.go#L68), so maybe make sense try increased value. Also, try fixed number of HTTP workers like this: `--output-http-workers <number>`.

What are the average requests per second? I'm thinking about situation when It kills all the workers due inactivity (this is not expected behavior, just trying to imagine possible ways), if so, fixed number of workers should help.

Thanks!

**Comment by exklamationmark** [comment] 2016-09-23 04:13
Hi @buger :D Thanks for getting back.

I only need to forward 10 rps, but need to do this reliably for a week (testing some drop-in replacement of a service).

So far, gor has not stopped since i increase timeout to 60s.

I am still curious on how it exited with a lower timeout.
What I expect is that the request is either dropped or retried, and there's some log about that.
Can u point me to where the worker management code is?
Maybe I can play around with the code & see where the exit point is.

P.S: Would it be better to declare the timeout in settings.go?, [like this](https://github.com/exklamationmark/gor/commit/34f93b73e62b9deadb595939ddf1d5551cfdd466)

**Comment by exklamationmark** [comment] 2016-09-23 06:30
Also would 2 gor listening on the same port interfere with each other in anyway?

**Comment by buger** [comment] 2016-09-26 18:02
> P.S: Would it be better to declare the timeout in settings.go?, like this

Yes, you are right, I will make this change. 

> Also would 2 gor listening on the same port interfere with each other in anyway?

They should not, at least from design point, but I'm not sure about libpcap traffic interception, so answer is: I have not idea :)


You can try to increase verbosity using `--debug --verbose` flags, also you can try `--stats --output-http-stats`.

**Comment by exklamationmark** [comment] 2016-09-27 06:29
Thanks. I have sent the [PR for the flag](https://github.com/buger/gor/pull/371)

Will get back once I figured out why it crash.

**Comment by exklamationmark** [comment] 2016-09-29 15:36
Hi,

Basically I got a SIGTERM while running :)

This happen repeatedly when I run `gor` inside a docker, a guess could be hitting some docker limit.
Unfortunately I won't be able to go further than this.

Anw, what do u think of adding a log line at the [signal handling, before `finalize()`](https://github.com/buger/gor/blob/master/gor.go#L81) ?

**Comment by buger** [comment] 2016-12-28 12:57
Will close it for now, because I can't replicate

**Closed** 2020-09-16 16:08 UTC
