### ISSUE TITLE
PANIC: pkg: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aalexgabi** [buger/goreplay#610] opened 2018-10-03 10:06 UTC
When I execute many requests very fast: by using |10000% modifier for input file I get this:
```
2018/10/03 12:04:31 [HTTPClient] Response:  
2018/10/03 12:04:31 PANIC: pkg: runtime error: invalid memory address or nil pointer dereference goroutine 2326 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc832eb7c68, 0xc832eb7c80)
	/go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc8200100d0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
crypto/tls.(*Conn).writeRecord(0xc831bff500, 0xc82ac74a16, 0xc82ac74a00, 0x9c, 0x9c, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:769 +0x542
crypto/tls.(*Conn).clientHandshake(0xc831bff500, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:147 +0xfba
crypto/tls.(*Conn).Handshake(0xc831bff500, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1033 +0xec
main.(*HTTPClient).Connect(0xc825c6ab80, 0x7fe6b8478b58, 0xc831198230)
	/go/src/github.com/buger/goreplay/http_client.go:98 +0x38a
main.(*HTTPClient).Send(0xc825c6ab80, 0xc82009a7bf, 0x231, 0x231, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/http_client.go:154 +0x32b5
main.(*HTTPOutput).sendRequest(0xc82008c500, 0xc825c6ab80, 0xc82009a780, 0x270, 0x270)
	/go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).startWorker(0xc82008c500)
	/go/src/github.com/buger/goreplay/output_http.go:125 +0x1c7
created by main.(*HTTPOutput).workerMaster
	/go/src/github.com/buger/goreplay/output_http.go:99 +0x85
```

**Comment by aalexgabi** [comment] 2018-10-03 10:33
I forgot to mention that I use a middleware

**Comment by wluo** [comment] 2018-10-06 06:36
+1 on the same stack trace, at 200% and 400% also.

**Comment by wluo** [comment] 2018-10-06 06:46
I think the bug is that you're incrementing `i` inside [this for-loop in `proto.go`](https://github.com/buger/goreplay/blob/652e589e2b71d5dfa4d2a70431d21b108a5e471e/proto/proto.go#L89) without checking if `i >= len(payload)` or not, so a malformed payload will cause an index out of range error. You did check that in the outer loop but not the inner loop where `i` can still be incremented beyond `len(payload)`.

**Comment by slimus** [comment] 2020-06-03 10:25
Hi @aalexgabi and @wluo . This is duplicate of #545. Please try version v1.0.0 or master branch

**Closed by slimus** 2020-06-03 10:25 UTC

**Comment by wluo** [comment] 2020-06-03 15:04
Thanks for the heads-up @slimus!
