### ISSUE TITLE
gor cannot replay every request,and is just for test?

### ISSUE THREAD

**Issue by NealLee** [buger/goreplay#355] opened 2016-08-05 07:42 UTC
when I replay the same out-put-file ,I get the different data count. is gor can not guarantee that every request will be send?

**Comment by buger** [comment] 2016-08-06 13:18
When you tell different, how much difference is, and what is the total number of requests?

By design, it should replay all recorded files. Thanks!

**Comment by NealLee** [comment] 2016-08-09 03:34
I use the akka-http to receive the request and the save to mongodb ,and i get the diffrent result:
akka-http:  two json parse error 
125421  
125463
125463
125463
125443
125444
125394
125481
125488

when I delete the error data,then get:
125463
125483
125463
125463

125483
125483
125413
125483
[request4event60mb1.gor.zip](https://github.com/buger/gor/files/408162/request4event60mb1.gor.zip)


it's very strange ,i‘m confused about it so much.

**Comment by buger** [comment] 2016-08-10 09:14
Can it be that your app can't handle such request rate? 
I would suggest you try to slowdown replay rate and check results after. 

For example:
```
# This will slowdown replay rate by 10x
gor --input-file "requests.gor|10%" --output-http ...
```

**Comment by NealLee** [comment] 2016-08-12 03:40
no，i'm sure it's not this reasion , and i retry the case you that you tell me, it doesn't make any difference! I doubt whether the 200kb litmit cause this question？the request file is from the --input-raw,and i've already update the file ,you can try this case,and repeat the problem.

**Comment by buger** [comment] 2016-08-31 15:08
Sorry for the late response!

Actually it is quite weird, the file you send me to have 21154 requests, mostly POST, and few OPTIONS.
```bash
cat -v issue_355_requests.gor | grep "HTTP/1.0" | wc -l
21154
```
Numbers you shown above does not make much sense...

Did you consider that your app or Mongo itself can drop requests as well?

I made few fixed recently, make sense to try this binary as well:
[gor_fix_replayed_header_x64.tar.gz](https://github.com/buger/gor/files/447576/gor_fix_replayed_header_x64.tar.gz)

Thank you so much for detailed feedback!

**Comment by buger** [comment] 2016-12-27 17:17
Closing for now

**Closed by buger** 2016-12-27 17:17 UTC
