### ISSUE TITLE
Q: Is this project still active?

### ISSUE THREAD

**Issue by StanleyP** [buger/goreplay#901] opened 2021-02-11 08:50 UTC
Hello,

I know we all live in a difficult times right now but may I very politely ask if this project is still under active development?

I hit some major issues using goreplay (https://github.com/buger/goreplay/issues/894, https://github.com/buger/goreplay/issues/900) and if this is not solved I will unfortunately have to look for alternative solution.

I think it would be real pity, because this project has tremendous potential for QA and for auditing and already has some unique features that have no parity in existing software.

Take care,
Stanislav Pavlíček

**Comment by urbanishimwe** [comment] 2021-02-11 10:04
@StanleyP yes it is.
As far as I know, we tend to fix issues instantly when we find their root causes. It is just that, it basically takes an amount of time to get the root cause of the issue, because of differences in data, complexities of protocols, and differences in environments.

E.g: a lot of issues related to #894 were fixed using the same flags commented on #894, [turned out](https://github.com/buger/goreplay/issues/894#issuecomment-770726016) your server was using another protocol(proxy + HTTP) that our parsers don't work with. you sent us a pcap file containing some messages and we [parsed it successfully](https://github.com/buger/goreplay/issues/894#issuecomment-774618758) the reply you provided on the comment was not mentioning further information about that specific issue, so we thought, the real issue is fixed in v1.3rc1, but you can't use that version because of #900. the information in #900  (an error that causes panic) did not add up(that's why we gave it lower priority than the others we have in our backlog).

I hope this clarifies!

**Comment by StanleyP** [comment] 2021-02-11 11:03
Ok, thanks for explanation and I am really glad that goreplay is still alive and well!
Kind regards,
Stanislav Pavlíček

**Closed** 2021-02-11 11:03 UTC
