### ISSUE TITLE
gorv1.3rc1: crash when using middleware

### ISSUE THREAD

**Issue by StanleyP** [buger/goreplay#900] opened 2021-02-08 13:27 UTC
I tried to use gorv1.3rc1 with middleware but it crashes as soon as request is captured:

```
2021/02/08 11:24:07 [PPID 749 and PID 930] Version:1.2.0
panic: runtime error: index out of range [296] with length 296

goroutine 13 [running]:
encoding/hex.Decode(0xc0002f6000, 0x128, 0x128, 0xc0002f4000, 0x252, 0x253, 0x0, 0x0, 0x0)
        /usr/local/go/src/encoding/hex/hex.go:69 +0x22b
main.(*Middleware).read(0xc00007cdc0, 0x10fe040, 0xc000010178)
        /go/src/github.com/buger/goreplay/middleware.go:107 +0x159
created by main.NewMiddleware
        /go/src/github.com/buger/goreplay/middleware.go:42 +0x2e3
```

My middleware is in nodejs and I tried to strip it down as much as possible, but crash still occurs. The crash seems to be in gor itself. My current stripped down MW is:

```javascript
var gor = require("goreplay_middleware");
  
gor.init();

gor.on('message', function(m) {
  return m;
})
```

The command that I use to invoke gor is:

```bash
exec $gor_bin \
  -input-raw 127.0.0.1:8008 \
  -input-raw-protocol http \
  -input-raw-track-response \
  -middleware $wd/mwfilter.sh \
  -output-stdout
```
With latest released version (v1.2.0) this setup including middleware works OK.

**Comment by urbanishimwe** [comment] 2021-02-13 10:22
@StanleyP The issue is fixed on the master branch, the last version doesn't have the fix!

**Comment by StanleyP** [comment] 2021-02-15 12:10
Guys, I can confirm that latest gor-master with my PROXY patch works OK! Thank you very much for support!!!
We can close this issue now.

**Closed** 2021-02-15 12:12 UTC
Labels: older version
