### ISSUE TITLE
Request error(EOF) with HTTP output replay

### ISSUE THREAD

**Issue by saikatharryc** [buger/goreplay#750] opened 2020-05-17 06:49 UTC
I'm trying to replay from file and also tried direct along with capturing.
it's not happening.
NOTE: I'm trying to replay in some webhook site. which takes almost every kind of request (HTTP type)

here is some verbose log:

```
root@development-api-6ccfbd9d5c-bpl5h:/# ./gor --input-file requests_0.log --output-http "https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808"
Version: 1.0.0
2020/05/17 06:44:55 Error when sending  EOF 2020-05-17 06:44:55.05138519 +0000 UTC m=+0.900381044
2020/05/17 06:44:58 Error when sending  EOF 2020-05-17 06:44:58.313977729 +0000 UTC m=+4.162973676
2020/05/17 06:45:09 Error when sending  EOF 2020-05-17 06:45:09.365738258 +0000 UTC m=+15.214734130
^Croot@development-api-6ccfbd9d5c-bpl5h:/usr/src/app# ./gor --input-file requests_0.log --output-http "https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808" -verbose
Version: 1.0.0
[DEBUG][PID 659][1589697930344132212][1589697930344.132080ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697930516854792][172.722580ms] [HTTPClient] Wrapping socket in TLS webhook.site

[DEBUG][PID 659][1589697930852924597][336.069805ms] [HTTPClient] Successfully wrapped in TLS
2020/05/17 06:45:31 Error when sending  EOF 2020-05-17 06:45:31.028954437 +0000 UTC m=+0.697013197
[DEBUG][PID 659][1589697931029055284][176.130687ms] Request error: EOF
[DEBUG][PID 659][1589697933813823345][2784.768061ms] [HTTPClient] connection closed, reconnecting
[DEBUG][PID 659][1589697933813853350][0.030005ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697933813962010][0.108660ms] [HTTP] Disconnected:  https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697933991222450][177.260440ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697934337744985][346.522535ms] [HTTPClient] Successfully wrapped in TLS
2020/05/17 06:45:34 Error when sending  EOF 2020-05-17 06:45:34.517594646 +0000 UTC m=+4.185653649
[DEBUG][PID 659][1589697934517664397][179.919412ms] Request error: EOF
[DEBUG][PID 659][1589697936893191305][2375.526908ms] [HTTPClient] connection closed, reconnecting
[DEBUG][PID 659][1589697936893224714][0.033409ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697936893377615][0.152901ms] [HTTP] Disconnected:  https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697937067123847][173.746232ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697937403970910][336.847063ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697937905533491][501.562581ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697937944043354][38.509863ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938073474997][129.431643ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938115343308][41.868311ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938121891038][6.547730ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938129619992][7.728954ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938179471467][49.851475ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938288443322][108.971855ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938297486077][9.042755ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938310463648][12.977571ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938358656817][48.193169ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938400495177][41.838360ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697938450870438][50.375261ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938468982736][18.112298ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697938472988692][4.005956ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938552183806][79.195114ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938624042013][71.858207ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938624835367][0.793354ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697938657993560][33.158193ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697938708009011][50.015451ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697938726997683][18.988672ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697938796675223][69.677540ms] [HTTPClient] Connecting: https://webhook.site/d149becc-07a3-4e40-8963-677ed9571808
[DEBUG][PID 659][1589697938845919576][49.244353ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697938960317886][114.398310ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697938969763317][9.445431ms] [HTTPClient] Wrapping socket in TLS webhook.site
[DEBUG][PID 659][1589697939066379146][96.615829ms] [HTTPClient] Successfully wrapped in TLS
[DEBUG][PID 659][1589697939305811488][239.432342ms] [HTTPClient] Successfully wrapped in TLS
2020/05/17 06:45:45 Error when sending  EOF 2020-05-17 06:45:45.547681311 +0000 UTC m=+15.215740199
[DEBUG][PID 659][1589697945547720972][6241.909484ms] Request error: EOF
```

**Comment by urbanishimwe** [comment] 2020-05-29 23:07
The problem might be that the `.gor input file` is empty or has a bad format and the other most likely cause of your problem is because the server is closing the connection. Rate limiting is one possible reason for this.

does this issue got reproduced with other output servers?

**Comment by urbanishimwe** [comment] 2020-11-04 09:18
closing this since HTTP output impls was modified!

**Closed by urbanishimwe** 2020-11-04 09:18 UTC
Labels: needs investigation
